### ISSUE TITLE
Feature request: Feature parity with pavucontrol ( or maybe just a few good features )

### ISSUE THREAD

**Issue by Silverdev2482** [saivert/pwvucontrol#6] opened 2023-12-09 01:30 UTC
I'm not sure if this is a good idea or all features are necessary but some would be really nice.
Here is a list of features that are missing and their subjective importance

- [x]  Input Device Tab - This seems very useful, especially for configuring volumes
- [x] Configuration Tab - Could be useful but not necessary
- [ ] Advanced drop down menu - I'm not sure if anything appears in here beside latency offset which likely is used rarely outside professional contexts
- [x] Port selector on input/output - Useful but usually only one port available for a device usually

**Comment by saivert** [comment] 2023-12-20 21:23
Added cards tab so you can change profile.

**Comment by saivert** [comment] 2023-12-22 22:14
Just did a huge code reorganization and clean up so hopefully easier for other contributors to navigate the code now.

**Comment by Silverdev2482** [comment] 2023-12-30 22:13
I edited the original post to make it a task list. I personally would love the input tab, but is the advanced drop down even worth implementing?

**Comment by Silverdev2482** [comment] 2023-12-30 22:16
On that note do we want complete parity at all? I feel like a decision should be made on this.

**Comment by saivert** [comment] 2023-12-30 22:48
Making task lists is all fine and good but I'm aware of what I want/need to implement here. This is still just my personal hobby project and there has been zero pull requests so far.

**Comment by Silverdev2482** [comment] 2023-12-31 14:45
I wish I could help but I don't know rust. Maybe I could learn? however that would take a while. I don't even know c.

**Comment by saivert** [comment] 2024-04-28 11:08
Just added port/route selection to sinks.

**Comment by saivert** [comment] 2024-04-29 18:38
Input device tab has been added.

**Comment by RamKromberg** [comment] 2024-06-08 20:55
Is over-amplification (beyond 100%) possible with pipewire?

**Comment by Silverdev2482** [comment] 2024-06-09 00:19
Yes it is, you can use wpctl status to get all your inputs, here is mine:
```
[silverdev2482@Desktop-SD:~]$ wpctl status
PipeWire 'pipewire-0' [1.0.6, silverdev2482@Desktop-SD, cookie:2681101611]
 └─ Clients:
        33. .xdg-desktop-portal-hyprland-wrapped [1.0.6, silverdev2482@Desktop-SD, pid:1805]
        34. WirePlumber                         [1.0.6, silverdev2482@Desktop-SD, pid:1814]
        42. WirePlumber [export]                [1.0.6, silverdev2482@Desktop-SD, pid:1814]
        43. pipewire                            [1.0.6, silverdev2482@Desktop-SD, pid:1852]
        44. waybar                              [1.0.6, silverdev2482@Desktop-SD, pid:1728]
        64. Firefox                             [1.0.6, silverdev2482@Desktop-SD, pid:1717]
        65. .pwvucontrol-wrapped                [1.0.6, silverdev2482@Desktop-SD, pid:2485]
        67. .pwvucontrol-wrapped                [1.0.6, silverdev2482@Desktop-SD, pid:2485]
        70. .pwvucontrol-wrapped                [1.0.6, silverdev2482@Desktop-SD, pid:2485]
        71. .pwvucontrol-wrapped                [1.0.6, silverdev2482@Desktop-SD, pid:2485]
        93. .pwvucontrol-wrapped                [1.0.6, silverdev2482@Desktop-SD, pid:2485]
       106. wpctl                               [1.0.6, silverdev2482@Desktop-SD, pid:9739]

Audio
 ├─ Devices:
 │      46. CMTECK                              [alsa]
 │      47. Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] [alsa]
 │      48. Family 17h (Models 00h-0fh) HD Audio Controller [alsa]
 │  
 ├─ Sinks:
 │  *   51. Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo [vol: 0.96]
 │  
 ├─ Sources:
 │  *   49. CMTECK                       Mono   [vol: 1.00]
 │      52. Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo [vol: 1.00]
 │  
 ├─ Filters:
 │  
 └─ Streams:
        69. pwvucontrol-peak-detect                                     
            100. input_FL        < Firefox:output_FL	[paused]
            101. monitor_FL     
            102. input_FR        < Firefox:output_FR	[paused]
            103. monitor_FR     
        73. pwvucontrol-peak-detect                                     
             75. input_FL        < ALC892 Analog:monitor_FL	[active]
             76. monitor_FL     
             77. input_FR        < ALC892 Analog:monitor_FR	[active]
             78. monitor_FR     
        82. pwvucontrol-peak-detect                                     
             68. input_FL       
             72. input_FR       
             81. monitor_FL     
             86. monitor_FR     
        84. Firefox                                                     
             66. output_FR       > ALC892 Analog:playback_FR	[paused]
             74. output_FL       > ALC892 Analog:playback_FL	[paused]
        92. Firefox                                                     
             95. output_FL       > ALC892 Analog:playback_FL	[paused]
             96. output_FR       > ALC892 Analog:playback_FR	[paused]
        97. pwvucontrol-peak-detect                                     
             88. monitor_FR     
             89. input_FL        < Firefox:output_FL	[paused]
             91. input_FR        < Firefox:output_FR	[paused]
             99. monitor_FL     

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sources:
 │  
 ├─ Filters:
 │  
 └─ Streams:

Settings
 └─ Default Configured Devices:
         0. Audio/Sink    alsa_output.pci-0000_29_00.3.analog-stereo
         1. Audio/Source  alsa_input.usb-CMTECK_Co._Ltd._CMTECK_000000000000-00.mono-fallback
```
From there you can can the volume with:
`wpctl get-volume ID`
As far as I know you can't set or get the volume of anything in streams that is nested, eg I can set the volume of node 84 or 92, but not 66 or 74.
And you set it with:
`wpctl set-volume ID VOLUME`
Volume is a decimal by default, but can be changed to a percent by adding a percent symbol. you also can relatively change volume by suffixing ( not prefixing ) it with a plus or minus

**Comment by Silverdev2482** [comment] 2024-06-09 00:20
pwvucontrol hasn't updated on nixos unstable, and I haven't gotten to patching nixpkgs so no updates on DRG crashing pwvucontrol.

**Comment by saivert** [comment] 2024-06-09 08:20
I will create a new catch-all thread for general support so as to not pollute the issue tracker with non-bug / user support related stuff.
This is a tracking issue for feature parity with pavucontrol only which has concluded.
Closing.

**Comment by RamKromberg** [comment] 2024-06-09 09:26
> pwvucontrol hasn't updated on nixos unstable, and I haven't gotten to patching nixpkgs so no updates on DRG crashing pwvucontrol.

@Silverdev2482 Actually 0.4.1 was available even on stable since around last week at least: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/audio/pwvucontrol/default.nix

Not sure why about "About pwvucontrol" popup says it's 0.1.0 though...

> not pollute the issue tracker with non-bug / user support related stuff.
This is a tracking issue for feature parity with pavucontrol only which has concluded.
Closing.

@saivert To clarify, I was asking since over-amplification is available on pavucontrol (lets you raise the volume slider over 100%) so I wasn't clear why it's missing from pwvucontrol (seeing how the slider only makes it to 100%). Now that I tried using wpctl like @Silverdev2482 suggested and noticed it doesn't work there either, I suspect it's probably a pipewire bug / missing feature (or at least, a very common implementation bug) rather than (just) a pwvucontrol.

Regardless, the unfortunate TL;DR of closing the feature request as is (for me at least) is that if it works in pavucontrol but doesn't work in pwvucontrol, use pavucontrol.

**Comment by saivert** [comment] 2024-06-09 13:22
Over-amplification is basically using software mixing to raise the waveform and more often than not cause distortion. I can implement support for it.

It was unfortunate that the original poster didn't include it as a point. I too hastily closed the issue.

**Comment by RamKromberg** [comment] 2024-06-09 15:11
@saivert oh I wasn't criticizing the decision to implement it or not. I was just being grumpy and confused about the premature claim of feature parity combined with the suggestion wpctl should allow it even though it clearly didn't. The two comments actually had me waste half-an-hour on three separate machines (a nixos desktop, a nixos laptop and a debian box) doing iterations of `wpctl set-volume 61 150%+` (150%+, 150+%, +150% and various values and sinks) before concluding there's a miscommunication and it's just not a supported feature...

Anyhow, there's nothing wrong about not implementing yet-another low-priority feature request. It just needed to be clarified as a _caveat emptor_ for any would-be user scratching their heads trying to debug why their volume slider isn't going over 100% and that it's not them doing something wrong, that it's not a bug and that it's perfectly fine to just continue using pavucontrol until such a time when someone decides it's worth their time to implement the feature.

Regardless, thanks for pwvucontrol. It's a fine piece of software that I use almost all the time and only reach for pavucontrol on very rare occasions. Take your time and just keep having fun with it. If someone REALLY needs it, they'll write a pull request ;)

**Comment by saivert** [comment] 2024-06-11 16:27
I have added support for over-amplification which is ready to rest in main branch right now. You must enable it from the hamburger menu.

**Comment by saivert** [comment] 2024-06-12 17:15
@RamKromberg 

Over-amplification works for devices as well.
![image](https://github.com/saivert/pwvucontrol/assets/63738/b4ad035d-97d0-43ea-b616-cad4e3632778)



Output from `wpctl`:

    ├─ Sinks:
    │  *   79. Built-in Audio Analog Stereo        [vol: 1.22]


And yes you are using a broken theme which doesn't style popovers correctly.

Please file further actual bug reports as a new issue. Questions are asked in Discussions area.

Closing...

**Closed by saivert** 2024-06-12 17:15 UTC
